name: Deploy via rsync

on:
  push:
    branches:
      - master


jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Kodni yuklash
        uses: actions/checkout@v3

      - name: Rsync exclude list yaratish
        run: |
          git ls-files --others --ignored --exclude-standard > .rsync-exclude

      - name: Rsync orqali loyihani serverga yuborish (root bilan)
        run: |
          sudo rsync -avz --delete --exclude-from='.rsync-exclude' ./ /var/www/goethe-back-end-master/
      - name: Laravel ruxsatlarini sozlash
        run: |
          sudo chown -R www-data:www-data /var/www/goethe-back-end-master/storage
          sudo chown -R www-data:www-data /var/www/goethe-back-end-master/bootstrap/cache
          sudo chmod -R ug+rwX /var/www/goethe-back-end-master/storage
          sudo chmod -R ug+rwX /var/www/goethe-back-end-master/bootstrap/cache
